# Use the official Node.js image as a parent image
FROM node:14

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Expose port 3000 for the React.js app
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]